const SB_URL="https://dctqsupasambvnyiyccn.supabase.co";
const SB_KEY="sb_publishable_XI18ywtyEn5lme6X6uTWBA_jgtvY3f5";
const headers=()=>({"apikey":SB_KEY,"Authorization":"Bearer "+(localStorage.getItem("mpc-access-token")||SB_KEY),"Content-Type":"application/json"});
async function sb(path,options={}){const r=await fetch(SB_URL+path,{...options,headers:{...headers(),...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(data?.message||data?.error_description||text||r.statusText);return data}
async function ensureAuth(){if(localStorage.getItem("mpc-access-token"))return;const r=await fetch(SB_URL+"/auth/v1/signup",{method:"POST",headers:{"apikey":SB_KEY,"Content-Type":"application/json"},body:"{}"});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error_description||"Anonymous sign-in failed");if(d.access_token)localStorage.setItem("mpc-access-token",d.access_token)}
function q(s){return document.querySelector(s)}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
async function collection(table){return sb("/rest/v1/"+table+"?select=*&order=created_at.desc")}
async function init(){try{await ensureAuth();initCases();initTerms();initGeneric("formulas","#formula-form","#formula-list",["formula-name","formula-value","formula-explanation","formula-usage"],["name","formula","explanation","usage"]);initGeneric("mistakes","#mistake-form","#mistake-list",["mistake-text","mistake-cause","mistake-lesson"],["mistake","cause","lesson"]);initGeneric("questions","#question-form","#question-list",["question-text","question-context","question-answer"],["question","context","answer"])}catch(e){console.error(e);document.querySelectorAll(".db-error").forEach(x=>x.textContent="Database error: "+e.message)}}
async function initCases(){const form=q("#case-form");if(!form)return;const list=q("#case-list"),file=q("#case-image"),preview=q("#case-preview");let selected=null;file?.addEventListener("change",()=>{selected=file.files?.[0]||null;if(!selected){preview.hidden=true;return}preview.src=URL.createObjectURL(selected);preview.hidden=false});async function render(){const data=await collection("cases");list.innerHTML=data?.length?data.map((x,i)=>'<article class="saved-card"><div class="saved-number">CASE '+String(i+1).padStart(2,"0")+'</div><h3>'+escapeHtml(x.problem)+'</h3><p><strong>Branches</strong><br>'+escapeHtml(x.branches).replace(/\n/g,"<br>")+'</p>'+(x.knowledge_used?'<p><strong>Knowledge</strong><br>'+escapeHtml(x.knowledge_used)+'</p>':"")+(x.formula_used?'<p><strong>Formula</strong><br>'+escapeHtml(x.formula_used)+'</p>':"")+(x.mistake_notes?'<p><strong>Mistake</strong><br>'+escapeHtml(x.mistake_notes)+'</p>':"")+(x.questions?'<p><strong>Questions</strong><br>'+escapeHtml(x.questions)+'</p>':"")+(x.solution?'<p><strong>Solution</strong><br>'+escapeHtml(x.solution)+'</p>':"")+(x.lesson?'<p><strong>Lesson</strong><br>'+escapeHtml(x.lesson)+'</p>':"")+(x.image_path?'<p><small>📷 '+escapeHtml(x.image_path)+'</small></p>':"")+'<button class="delete-button" type="button" data-case-delete="'+x.id+'">Xóa case</button></article>').join(""):'<p class="empty-state">Chưa có case nào.</p>'}form.addEventListener("submit",async e=>{e.preventDefault();const row={problem:q("#case-problem").value.trim(),branches:q("#case-branches").value.trim(),knowledge_used:q("#case-knowledge")?.value.trim()||"",formula_used:q("#case-formula")?.value.trim()||"",mistake_notes:q("#case-mistake")?.value.trim()||"",questions:q("#case-questions")?.value.trim()||"",solution:q("#case-solution")?.value.trim()||"",lesson:q("#case-lesson")?.value.trim()||""};if(!row.problem||!row.branches)return alert("Hãy nhập Problem và Branches.");if(selected){const path="anon/"+crypto.randomUUID()+"-"+selected.name.replace(/[^a-zA-Z0-9._-]/g,"_");const r=await fetch(SB_URL+"/storage/v1/object/case-images/"+path,{method:"POST",headers:{"apikey":SB_KEY,"Authorization":"Bearer "+localStorage.getItem("mpc-access-token"),"Content-Type":selected.type,"x-upsert":"false"},body:selected});if(!r.ok)throw new Error("Upload ảnh thất bại");row.image_path=path}await sb("/rest/v1/cases",{method:"POST",headers:{"Prefer":"return=minimal"},body:JSON.stringify(row)});form.reset();preview.hidden=true;selected=null;await render()});list.addEventListener("click",async e=>{const b=e.target.closest("[data-case-delete]");if(!b)return;await sb("/rest/v1/cases?id=eq."+b.dataset.caseDelete,{method:"DELETE"});render()});render()}
async function initTerms(){const form=q("#term-form");if(!form)return;const list=q("#term-list");async function render(){const data=await collection("terms");list.innerHTML=data?.length?data.map(x=>'<article class="term-card"><div><h3>'+escapeHtml(x.term)+'</h3><p>'+escapeHtml(x.explanation)+'</p></div><button class="delete-button" type="button" data-term-delete="'+x.id+'">Xóa</button></article>').join(""):'<p class="empty-state">Chưa có thuật ngữ.</p>'}form.addEventListener("submit",async e=>{e.preventDefault();const term=q("#term-name").value.trim(),explanation=q("#term-explanation").value.trim();if(!term||!explanation)return;await sb("/rest/v1/terms",{method:"POST",headers:{"Prefer":"return=minimal"},body:JSON.stringify({term,explanation})});form.reset();render()});list.addEventListener("click",async e=>{const b=e.target.closest("[data-term-delete]");if(!b)return;await sb("/rest/v1/terms?id=eq."+b.dataset.termDelete,{method:"DELETE"});render()});render()}
function initGeneric(table,formSelector,listSelector,ids,keys){const form=q(formSelector);if(!form)return;const list=q(listSelector);async function render(){const data=await collection(table);list.innerHTML=data?.length?data.map(x=>'<article class="saved-card"><h3>'+escapeHtml(x[keys[0]])+'</h3>'+keys.slice(1).map(k=>'<p><strong>'+escapeHtml(k)+'</strong><br>'+escapeHtml(x[k])+'</p>').join("")+'<button class="delete-button" type="button" data-generic-delete="'+x.id+'">Xóa</button></article>').join(""):'<p class="empty-state">Chưa có dữ liệu.</p>'}form.addEventListener("submit",async e=>{e.preventDefault();const row={};ids.forEach((id,i)=>row[keys[i]]=q("#"+id).value.trim());if(!row[keys[0]])return;await sb("/rest/v1/"+table,{method:"POST",headers:{"Prefer":"return=minimal"},body:JSON.stringify(row)});form.reset();render()});list.addEventListener("click",async e=>{const b=e.target.closest("[data-generic-delete]");if(!b)return;await sb("/rest/v1/"+table+"?id=eq."+b.dataset.genericDelete,{method:"DELETE"});render()});render()}
const geminiForm=q("#gemini-form");
if(geminiForm)geminiForm.addEventListener("submit",async e=>{e.preventDefault();const p=q("#gemini-prompt").value.trim();if(p)try{await navigator.clipboard.writeText(p)}catch{}window.open("https://gemini.google.com/","_blank","noopener,noreferrer")});
document.addEventListener("DOMContentLoaded",init);